### ISSUE TITLE
Unable to commit - Since the Upgrade

### ISSUE THREAD

**Issue by amitahire** [magit/magit#2127]
I am unable to commit anything ad I am getting this message

```
1 c:/cygwin64/bin/git.exe … commit -- Waiting for Emacs...

ERROR: Wrong type argument: arrayp, nilerror: There was a problem with the editor
 '"c:/Program Files (x86)/Emacs/emacs-24.5/bin/emacsclient.exe"'. 
Please supply the message using either -m or -F option.

```

I wanted to use cygwin with emacs, having set that, cygwin didnt see the windows git properly - hence I installed git for cygwin. Probably that's causing some issue? In my *exec-path* I have the path of cygwin-git.

I went through issues and found this link - https://github.com/magit/magit/issues/1998 -- Tried reinstaliing as suggested there, but I am still facing the same issue. With ``` M-x with-editor-debug ``` i get the following output 

```
with-editor: c:/EmacsHome/.emacs.d/elpa/with-editor-20150710.252/with-editor.el
emacs: c:/Program Files (x86)/Emacs/emacs-24.5/bin/emacs (24.5.1)
system:
  system-type: windows-nt
  system-configuration: i686-pc-mingw32
  system-configuration-options: --prefix=/c/usr --host=i686-pc-mingw32
server:
  server-running-p: t
  server-process: #<process server9788>
  server-use-tcp: t
  server-name: server9788
  server-socket-dir: nil

```
and also ``` M-x magit-version -->  Magit 20150729.518, Git 2.4.5, Emacs 24.5.1 ```

Any help will be appreciated. Also posted on Stackoverflow (http://emacs.stackexchange.com/questions/14331/magit-unable-to-commit) and Google groups, posted here only when I didnt get any response there.
